const PRODUCT_CATALOG_URL = process.env.VUE_APP_PRODUCT_CATALOG_URL
const SHOPPING_CART_URL = process.env.VUE_APP_SHOPPING_CART_URL
const STORE_CATALOG_URL = process.env.VUE_APP_STORE_CATALOG_URL

export {
    PRODUCT_CATALOG_URL,
    SHOPPING_CART_URL,
    STORE_CATALOG_URL,
}